# for module compiling
import os
Import('RTT_ROOT')

PROJECT = 'RK2108'
Export('PROJECT')
cwd = str(Dir('#'))
objs = []
list = os.listdir(cwd)

objs = SConscript(os.path.join(cwd, '../common/HalSConscript'), variant_dir = 'common/hal', duplicate=0)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs = objs + SConscript(os.path.join(RTT_ROOT, 'bsp/rockchip/common/drivers/SConscript'), variant_dir = 'common/drivers', duplicate=0)
objs = objs + SConscript(os.path.join(RTT_ROOT, 'third_party/SConscript'), variant_dir = 'third_party', duplicate=0)
objs = objs + SConscript(os.path.join(RTT_ROOT, 'applications/SConscript'), variant_dir = 'applications', duplicate=0)
objs = objs + SConscript(os.path.join(RTT_ROOT, 'bsp/rockchip/common/tests/SConscript'), variant_dir = 'common/tests', duplicate=0)
objs = objs + SConscript(os.path.join(RTT_ROOT, 'bsp/rockchip/common/fwmgr/SConscript'), variant_dir = 'common/fwmgr', duplicate=0)
objs = objs + SConscript(os.path.join(RTT_ROOT, 'examples/kernel/SConscript'), variant_dir = 'examples/kernel', duplicate=0)
objs = objs + SConscript(os.path.join(RTT_ROOT, 'examples/file/SConscript'), variant_dir = 'examples/file', duplicate=0)

Return('objs')
