Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

if GetDepend(['BT_ENABLED']) is not True:
    src = []
    CPPPATH = []

group = DefineGroup('BT_AP6212', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
