Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src  = Glob('*.c')
# src += Glob('resource/*.c')
CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = ['RT_USING_LVGL_CLOCK_DEMO1'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
